@extends('website.layout.app')

@section('title', __('messages.gantt_chart'))

@section('content')
    <div class="content-header d-flex justify-content-between align-items-center gap-3 flex-wrap">
        <div>
            <h2>{{ __('messages.gantt_chart') }}</h2>
            <p>{{ __('messages.visualize_manage_activities') }}</p>
        </div>
        <div class="d-flex align-items-center gap-2 gap-md-3 flex-wrap">
            <!-- View Mode Buttons -->
            <div class="btn-group" role="group" aria-label="View Mode">
                <button type="button" class="btn btn-outline-primary active" data-view="day">{{ __('messages.day') }}</button>
                <button type="button" class="btn btn-outline-primary" data-view="week">{{ __('messages.week') }}</button>
                <button type="button" class="btn btn-outline-primary" data-view="year">{{ __('messages.year') }}</button>
            </div>

            <!-- Add Activity Button -->
             @can('gantt', 'create')
            <button class="btn orange_btn py-2" data-bs-toggle="modal" data-bs-target="#addActivityModal">
                 <i class="fas fa-plus"></i>
                 {{ __('messages.add_activity') }}
            </button>
            @endcan
        </div>
    </div>

    <section class="px-md-4">
        <div class="container-fluid">
            <div class="card mb-4 border-0 shadow-sm">
                <div class="card-body">
                    <div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4">
                        <!-- Date Filter -->
                        <div class="d-flex align-items-center bg-light rounded p-1">
                            <select id="monthYearFilter" class="form-select border-0 bg-transparent fw-bold" style="width: auto;">
                                <!-- Options populated by JS -->
                            </select>
                        </div>
                    </div>
    
                    <!-- Legend -->
                    <div class="d-flex flex-wrap gap-4 mb-4">
                        <div class="d-flex align-items-center">
                            <span class="badge me-2 rounded-1" style="width: 15px; height: 15px; display: inline-block; background-color: #ced6e0;"></span>
                            <span class="text-muted">{{ __('messages.todo_planned') }}</span>
                        </div>
                        <div class="d-flex align-items-center">
                            <!-- Showing the blend of Orange (Progress) and Blue (Remaining) -->
                            <div class="d-flex border rounded-1 overflow-hidden me-2" style="width: 24px; height: 15px;">
                                <div style="width: 50%; background-color: #F2994A;"></div>
                                <div style="width: 50%; background-color: #4b7bec;"></div>
                            </div>
                            <span class="text-muted">{{ __('messages.in_progress') }}</span>
                        </div>
                        <div class="d-flex align-items-center">
                            <span class="badge me-2 rounded-1" style="width: 15px; height: 15px; display: inline-block; background-color: #26de81;"></span>
                            <span class="text-muted">{{ __('messages.completed_approved') }}</span>
                        </div>
                        <div class="d-flex align-items-center">
                            <span class="badge me-2 rounded-1" style="width: 15px; height: 15px; display: inline-block; background-color: #fc5c65;"></span>
                            <span class="text-muted">{{ __('messages.delayed_overdue') }}</span>
                        </div>
                    </div>
    
                    <!-- Gantt Chart Container -->
                    <div class="gantt-chart-wrapper position-relative" style="overflow-x: auto;">
                        <div id="ganttChart" class="gantt-chart border rounded">
                            <!-- Chart generated by JS -->
                            <div class="text-center p-5 text-muted">
                                <div class="spinner-border text-primary" role="status">
                                    <span class="visually-hidden">{{ __('messages.loading') }}</span>
                                </div>
                                <p class="mt-2">{{ __('messages.loading_chart') }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

<!-- Add Activity Modal -->
<div class="modal fade" id="addActivityModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <form> <!-- Form action removed, handled by JS -->
            <!-- Token handling done by JS (localStorage) -->
            <div class="modal-content">
                <div class="modal-header">
                    <style>
                        #addActivityModal .modal-header .btn-close {
                            position: static !important;
                            right: auto !important;
                            top: auto !important;
                            margin: 0 !important;
                        }

                        #addActivityModal .modal-header {
                            position: relative !important;
                        }
                    </style>
                    @if (app()->getLocale() == 'ar')
                        <div class="d-flex justify-content-between align-items-center w-100">
                            <h5 class="modal-title" id="activityModalTitle">{{ __('messages.add_activity') }}</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                    @else
                        <h5 class="modal-title" id="activityModalTitle">{{ __('messages.add_activity') }}</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    @endif
                </div>
                <div class="modal-body">
                    <input type="hidden" name="activity_id" id="activityId">
                    <div class="mb-3">
                        <label class="form-label">{{ __('messages.activity_name') }}</label>
                        <input type="text" name="name" class="form-control" placeholder="{{ __('messages.enter_activity_name') }}" required>
                    </div>
                    
                    <div class="mb-3">
                        <label class="form-label">{{ __('messages.description') }}</label>
                        <textarea name="description" class="form-control" rows="3" placeholder="{{ __('messages.enter_activity_description') }}"></textarea>
                    </div>

                    <h6 class="mt-4 mb-3 border-bottom pb-2">{{ __('messages.schedule') }}</h6>
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label class="form-label">{{ __('messages.start_date') }}</label>
                            <input type="date" name="start_date" id="startDate" class="form-control" required>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label class="form-label">{{ __('messages.end_date') }}</label>
                            <input type="date" name="end_date" id="endDate" class="form-control" required>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label class="form-label text-muted small">{{ __('messages.duration') }}</label>
                        <div id="durationDisplay" class="fw-bold text-primary">-</div>
                    </div>

                    <h6 class="mt-4 mb-3 border-bottom pb-2">{{ __('messages.resources') }}</h6>
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label class="form-label">{{ __('messages.workers') }}</label>
                            <input type="number" name="workers_count" class="form-control" value="0" min="0">
                        </div>
                        <div class="col-md-6 mb-3">
                            <label class="form-label">{{ __('messages.equipment') }}</label>
                            <input type="number" name="equipment_count" class="form-control" value="0" min="0">
                        </div>
                    </div>

                    <h6 class="mt-4 mb-3 border-bottom pb-2">{{ __('messages.status') }}</h6>
                    <div class="row">
                        <div class="col-12 mb-3">
                            <label class="form-label">{{ __('messages.status') }}</label>
                            <select name="status" class="form-select" required>
                                <option value="todo" selected>{{ __('messages.todo') }}</option>
                                <option value="in_progress">{{ __('messages.in_progress') }}</option>
                                <option value="complete">{{ __('messages.complete') }}</option>
                                <option value="approve">{{ __('messages.approve') }}</option>
                            </select>
                            <div class="form-text text-muted small mt-1">
                                {{ __('messages.progress_calculation_note') }}
                                <br>
                                {!! __('messages.complete_approve_note') !!}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{ __('messages.close') }}</button>
                    <button type="submit" class="btn btn-primary">{{ __('messages.save_activity') }}</button>
                </div>
            </div>
        </form>
    </div>
</div>

<!-- View Activity Modal -->
<div class="modal fade" id="viewActivityModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <style>
                    #viewActivityModal .modal-header .btn-close {
                        position: static !important;
                        right: auto !important;
                        top: auto !important;
                        margin: 0 !important;
                    }

                    #viewActivityModal .modal-header {
                        position: relative !important;
                    }
                </style>
                @if (app()->getLocale() == 'ar')
                    <div class="d-flex justify-content-between align-items-center w-100">
                        <h5 class="modal-title">{{ __('messages.activity_details') }}</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                @else
                    <h5 class="modal-title">{{ __('messages.activity_details') }}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                @endif
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label class="fw-bold form-label">{{ __('messages.activity_name') }}</label>
                    <p id="viewName" class="form-control-plaintext border-bottom pb-2">{{ __('messages.loading') }}</p>
                </div>
                
                <div class="mb-3">
                    <label class="fw-bold form-label">{{ __('messages.description') }}</label>
                    <p id="viewDescription" class="form-control-plaintext border-bottom pb-2 text-muted">{{ __('messages.no_description') }}</p>
                </div>

                <h6 class="mt-4 mb-3 border-bottom pb-2 text-primary">{{ __('messages.schedule') }}</h6>
                <div class="row">
                    <div class="col-6 mb-3">
                        <label class="small text-muted">{{ __('messages.start_date') }}</label>
                        <div id="viewStartDate" class="fw-medium"></div>
                    </div>
                    <div class="col-6 mb-3">
                        <label class="small text-muted">{{ __('messages.end_date') }}</label>
                        <div id="viewEndDate" class="fw-medium"></div>
                    </div>
                </div>

                <h6 class="mt-4 mb-3 border-bottom pb-2 text-primary">{{ __('messages.resources') }}</h6>
                <div class="row">
                    <div class="col-6 mb-3">
                        <label class="small text-muted">{{ __('messages.workers') }}</label>
                        <div id="viewWorkers" class="fw-medium">0</div>
                    </div>
                    <div class="col-6 mb-3">
                        <label class="small text-muted">{{ __('messages.equipment') }}</label>
                        <div id="viewEquipment" class="fw-medium">0</div>
                    </div>
                </div>

                <h6 class="mt-4 mb-3 border-bottom pb-2 text-primary">{{ __('messages.status') }}</h6>
                <div class="row align-items-center">
                    <div class="col-6">
                        <label class="small text-muted">{{ __('messages.progress') }}</label>
                        <div class="progress mt-1" style="height: 10px;">
                            <div id="viewProgressBar" class="progress-bar" role="progressbar" style="width: 0%"></div>
                        </div>
                        <small id="viewProgressText" class="d-block mt-1">0%</small>
                    </div>
                    <div class="col-6">
                        <label class="small text-muted">{{ __('messages.current_status') }}</label>
                        <span id="viewStatusBadge" class="badge bg-secondary d-table mt-1">{{ __('messages.unknown') }}</span>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{{ __('messages.close') }}</button>
            </div>
        </div>
    </div>
</div>

<style>
    .gantt-chart {
        display: grid;
        /* Grid columns handled by JS */
        min-width: 100%;
    }
    .gantt-header-cell {
        padding: 10px;
        text-align: center;
        border-right: 1px solid #eee;
        border-bottom: 1px solid #eee;
        background-color: #f8f9fa;
        font-weight: 500;
        font-size: 0.85rem;
    }
    .gantt-row {
        display: contents;
    }
    .gantt-cell {
        padding: 10px;
        border-right: 1px solid #f5f5f5;
        border-bottom: 1px solid #eee;
        height: 50px;
        position: relative;
    }
    .gantt-task-name {
        position: sticky;
        left: 0;
        background: white;
        z-index: 10;
        padding: 10px;
        border-right: 1px solid #ddd;
        border-bottom: 1px solid #eee;
        min-width: 200px;
        font-weight: 500;
        display: flex;
        align-items: center;
    }
    .gantt-bar-container {
        position: absolute;
        top: 50%;
        transform: translateY(-50%);
        height: 24px;
        z-index: 5;
        border-radius: 12px;
        overflow: hidden;
        display: flex;
        align-items: center;
        /* Width and Left handled by JS */
    }
    
    /* Status Colors */
    
    /* 1. Active Tasks: Orange (Progress) on Blue (Remaining) */
    .time-active {
        background-color: #4b7bec; 
    }
    .time-active .gantt-bar {
        background-color: #F2994A; 
    }

    /* 2. Future Tasks: Planned (Darker Gray as requested) */
    .time-future {
        background-color: #e2e6ea; /* Darker Background */
    }
    .time-future .gantt-bar {
        background-color: #adb5bd; /* Darker Bar */
    }
    
    /* 3. Delayed Tasks: Red */
    .time-delayed {
        background-color: #fadbd8; 
    }
    .time-delayed .gantt-bar {
        background-color: #fc5c65; 
    }
    
    /* 4. Completed/Approved Tasks: Green */
    .time-completed {
        background-color: #d1f2eb; 
    }
    .time-completed .gantt-bar {
        background-color: #26de81; 
    }
    
    /* Common Bar Styles */
    .gantt-bar {
        color: white;
        font-weight: bold;
        font-size: 11px;
        display: flex;
        align-items: center;
        justify-content: center;
        overflow: hidden;
        white-space: nowrap;
        height: 100%;
        box-shadow: 0 1px 3px rgba(0,0,0,0.1);
        transition: width 0.3s ease;
    }

    /* Current Date Line */
    .current-date-line {
        position: absolute;
        top: 0;
        bottom: 0;
        width: 2px;
        background-color: #FFC107; /* Yellow */
        z-index: 15;
        pointer-events: none;
        box-shadow: 0 0 5px rgba(0,0,0,0.2);
    }
    
    /* RTL Support */
    [dir="rtl"] .gantt-task-name { left: auto; right: 0; border-right: none; border-left: 1px solid #ddd; }
    [dir="rtl"] .current-date-line { left: auto; right: auto; } /* JS handles position */
    
    /* Modal Header RTL Fix */
    .modal-header .btn-close {
        margin: 0 !important; /* Force reset */
    }
</style>

@push('scripts')
<script>
    window.translations = {
        todo: "{{ __('messages.todo') }}",
        in_progress: "{{ __('messages.in_progress') }}",
        complete: "{{ __('messages.complete') }}",
        approve: "{{ __('messages.approve') }}",
        unknown: "{{ __('messages.unknown') }}",
        failed_load: "{{ __('messages.failed_load_activities') }}",
        failed_save: "{{ __('messages.failed_save_activity') }}",
        days: "{{ __('messages.days') }}",
        day: "{{ __('messages.day') }}",
        week: "{{ __('messages.week') }}",
        year: "{{ __('messages.year') }}",
        loading: "{{ __('messages.loading_chart') }}",
        edit_activity: "{{ __('messages.edit') }} {{ __('messages.activity_name') }}", // Construct "Edit Activity Name" conceptually
        add_activity: "{{ __('messages.add_activity') }}",
    };
</script>
<script src="{{ asset('assets/js/gantt-chart.js') }}"></script>
<script>
    // Duration Logic
    document.addEventListener('DOMContentLoaded', function() {
        const startInput = document.getElementById('startDate');
        const endInput = document.getElementById('endDate');
        const durationDisplay = document.getElementById('durationDisplay');

        function calculateDuration() {
            if (startInput.value && endInput.value) {
                const start = new Date(startInput.value);
                const end = new Date(endInput.value);
                
                // Difference in time
                const timeDiff = end.getTime() - start.getTime();
                
                // Difference in days (inclusive)
                if (timeDiff >= 0) {
                    const daysDiff = (timeDiff / (1000 * 3600 * 24)) + 1;
                    durationDisplay.textContent = Math.round(daysDiff) + " " + "{{ __('messages.days') }}";
                } else {
                    durationDisplay.textContent = "{{ __('messages.invalid_date_range') }}";
                }
            } else {
                durationDisplay.textContent = "-";
            }
        }

        startInput.addEventListener('change', calculateDuration);
        endInput.addEventListener('change', calculateDuration);
    });
</script>
@endpush
@endsection
