@extends('website.layout.app')

@section('title', 'Gantt Chart')

@section('content')
    <div class="content-header d-flex justify-content-between align-items-center gap-3 flex-wrap">
        <div>
            <h2>Gantt Chart</h2>
            <p>Visualize and manage project activities</p>
        </div>
        <div class="d-flex align-items-center gap-2 gap-md-3 flex-wrap">
            <!-- View Mode Buttons -->
            <div class="btn-group" role="group" aria-label="View Mode">
                <button type="button" class="btn btn-outline-primary active" data-view="day">Day</button>
                <button type="button" class="btn btn-outline-primary" data-view="week">Week</button>
                <button type="button" class="btn btn-outline-primary" data-view="year">Year</button>
            </div>

            <!-- Add Activity Button -->
            <button class="btn orange_btn py-2" data-bs-toggle="modal" data-bs-target="#addActivityModal">
                 <i class="fas fa-plus"></i>
                 Add Activity
            </button>
        </div>
    </div>

    <section class="px-md-4">
        <div class="container-fluid">
            <div class="card mb-4 border-0 shadow-sm">
                <div class="card-body">
                    <div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4">
                        <!-- Date Filter -->
                        <div class="d-flex align-items-center bg-light rounded p-1">
                            <select id="monthYearFilter" class="form-select border-0 bg-transparent fw-bold" style="width: auto;">
                                <!-- Options populated by JS -->
                            </select>
                        </div>
                    </div>
    
                    <!-- Legend -->
                    <div class="d-flex flex-wrap gap-4 mb-4">
                        <div class="d-flex align-items-center">
                            <span class="badge bg-secondary me-2 rounded-1" style="width: 15px; height: 15px; display: inline-block;"></span>
                            <span class="text-muted">Planned</span>
                        </div>
                        <div class="d-flex align-items-center">
                            <span class="badge bg-primary me-2 rounded-1" style="width: 15px; height: 15px; display: inline-block;"></span>
                            <span class="text-muted">In Progress</span>
                        </div>
                        <div class="d-flex align-items-center">
                            <span class="badge bg-success me-2 rounded-1" style="width: 15px; height: 15px; display: inline-block;"></span>
                            <span class="text-muted">Completed</span>
                        </div>
                        <div class="d-flex align-items-center">
                            <span class="badge bg-danger me-2 rounded-1" style="width: 15px; height: 15px; display: inline-block;"></span>
                            <span class="text-muted">Delayed</span>
                        </div>
                    </div>
    
                    <!-- Gantt Chart Container -->
                    <div class="gantt-chart-wrapper position-relative" style="overflow-x: auto;">
                        <div id="ganttChart" class="gantt-chart border rounded">
                            <!-- Chart generated by JS -->
                            <div class="text-center p-5 text-muted">
                                <div class="spinner-border text-primary" role="status">
                                    <span class="visually-hidden">Loading...</span>
                                </div>
                                <p class="mt-2">Loading chart...</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

<!-- Add Activity Modal -->
<div class="modal fade" id="addActivityModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <form> <!-- Form action removed, handled by JS -->
            <!-- Token handling done by JS (localStorage) -->
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="activityModalTitle">Add Activity</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="activity_id" id="activityId">
                    <div class="mb-3">
                        <label class="form-label">Activity Name</label>
                        <input type="text" name="name" class="form-control" placeholder="Enter activity name" required>
                    </div>
                    
                    <div class="mb-3">
                        <label class="form-label">Description</label>
                        <textarea name="description" class="form-control" rows="3" placeholder="Enter activity description"></textarea>
                    </div>

                    <h6 class="mt-4 mb-3 border-bottom pb-2">Schedule</h6>
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label class="form-label">Start Date</label>
                            <input type="date" name="start_date" id="startDate" class="form-control" required>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label class="form-label">End Date</label>
                            <input type="date" name="end_date" id="endDate" class="form-control" required>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label class="form-label text-muted small">Duration</label>
                        <div id="durationDisplay" class="fw-bold text-primary">-</div>
                    </div>

                    <h6 class="mt-4 mb-3 border-bottom pb-2">Resources</h6>
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label class="form-label">Workers</label>
                            <input type="number" name="workers_count" class="form-control" value="0" min="0">
                        </div>
                        <div class="col-md-6 mb-3">
                            <label class="form-label">Equipment</label>
                            <input type="number" name="equipment_count" class="form-control" value="0" min="0">
                        </div>
                    </div>

                    <h6 class="mt-4 mb-3 border-bottom pb-2">Status & Progress</h6>
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label class="form-label">Progress (%)</label>
                            <input type="number" name="progress" class="form-control" min="0" max="100" value="0" required>
                        </div>
                        <div class="col-md-6 mb-3">
                            <label class="form-label">Status</label>
                            <select name="status" class="form-select">
                                <option value="" selected>Auto-calculate</option>
                                <option value="planned">Planned</option>
                                <option value="in_progress">In Progress</option>
                                <option value="completed">Completed</option>
                                <option value="delayed">Delayed</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save Activity</button>
                </div>
            </div>
        </form>
    </div>
</div>

<!-- View Activity Modal -->
<div class="modal fade" id="viewActivityModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Activity Details</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="mb-3">
                    <label class="fw-bold form-label">Activity Name</label>
                    <p id="viewName" class="form-control-plaintext border-bottom pb-2">Loading...</p>
                </div>
                
                <div class="mb-3">
                    <label class="fw-bold form-label">Description</label>
                    <p id="viewDescription" class="form-control-plaintext border-bottom pb-2 text-muted">No description</p>
                </div>

                <h6 class="mt-4 mb-3 border-bottom pb-2 text-primary">Schedule</h6>
                <div class="row">
                    <div class="col-6 mb-3">
                        <label class="small text-muted">Start Date</label>
                        <div id="viewStartDate" class="fw-medium"></div>
                    </div>
                    <div class="col-6 mb-3">
                        <label class="small text-muted">End Date</label>
                        <div id="viewEndDate" class="fw-medium"></div>
                    </div>
                </div>

                <h6 class="mt-4 mb-3 border-bottom pb-2 text-primary">Resources</h6>
                <div class="row">
                    <div class="col-6 mb-3">
                        <label class="small text-muted">Workers</label>
                        <div id="viewWorkers" class="fw-medium">0</div>
                    </div>
                    <div class="col-6 mb-3">
                        <label class="small text-muted">Equipment</label>
                        <div id="viewEquipment" class="fw-medium">0</div>
                    </div>
                </div>

                <h6 class="mt-4 mb-3 border-bottom pb-2 text-primary">Status</h6>
                <div class="row align-items-center">
                    <div class="col-6">
                        <label class="small text-muted">Progress</label>
                        <div class="progress mt-1" style="height: 10px;">
                            <div id="viewProgressBar" class="progress-bar" role="progressbar" style="width: 0%"></div>
                        </div>
                        <small id="viewProgressText" class="d-block mt-1">0%</small>
                    </div>
                    <div class="col-6">
                        <label class="small text-muted">Current Status</label>
                        <span id="viewStatusBadge" class="badge bg-secondary d-table mt-1">Unknown</span>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<style>
    .gantt-chart {
        display: grid;
        /* Grid columns handled by JS */
        min-width: 100%;
    }
    .gantt-header-cell {
        padding: 10px;
        text-align: center;
        border-right: 1px solid #eee;
        border-bottom: 1px solid #eee;
        background-color: #f8f9fa;
        font-weight: 500;
        font-size: 0.85rem;
    }
    .gantt-row {
        display: contents;
    }
    .gantt-cell {
        padding: 10px;
        border-right: 1px solid #f5f5f5;
        border-bottom: 1px solid #eee;
        height: 50px;
        position: relative;
    }
    .gantt-task-name {
        position: sticky;
        left: 0;
        background: white;
        z-index: 10;
        padding: 10px;
        border-right: 1px solid #ddd;
        border-bottom: 1px solid #eee;
        min-width: 200px;
        font-weight: 500;
        display: flex;
        align-items: center;
    }
    .gantt-bar-container {
        position: absolute;
        top: 50%;
        transform: translateY(-50%);
        height: 24px;
        z-index: 5;
        border-radius: 12px;
        overflow: hidden;
        display: flex;
        align-items: center;
        /* Width and Left handled by JS */
    }
    .gantt-bar {
        height: 100%;
        border-radius: 12px;
        color: white;
        font-size: 11px;
        display: flex;
        align-items: center;
        justify-content: center;
        transition: width 0.3s ease;
    }
    
    /* Status Colors - Time Based Logic */
    
    /* Active/Past Tasks: Yellow (Progress) on Blue (Remaining) */
    .time-active {
        background-color: #4361ee; /* Blue for remaining */
    }
    .time-active .gantt-bar {
        background-color: #fdab3d; /* Orange/Yellow for completed */
    }

    /* Future Tasks: Red */
    .time-future {
        background-color: #ea5455; /* Red for future/planned */
    }
    .time-future .gantt-bar {
        background-color: #ea5455; /* Red (if any progress exists) */
    }
    
    /* Common Bar Styles */
    .gantt-bar {
        color: white;
        font-weight: bold;
        font-size: 11px;
        display: flex;
        align-items: center;
        justify-content: center;
        overflow: hidden;
        white-space: nowrap;
    }

    /* Current Date Line */
    .current-date-line {
        position: absolute;
        top: 0;
        bottom: 0;
        width: 2px;
        background-color: #FFC107; /* Yellow */
        z-index: 15;
        pointer-events: none;
        box-shadow: 0 0 5px rgba(0,0,0,0.2);
    }
    
    /* Current Date Line */
    .current-date-line {
        position: absolute;
        top: 0;
        bottom: 0;
        width: 2px;
        background-color: #FFC107; /* Yellow */
        z-index: 15;
        pointer-events: none;
        box-shadow: 0 0 5px rgba(0,0,0,0.2);
    }
    
    /* Label Removed as per request */

    /* RTL Support */
    [dir="rtl"] .gantt-task-name { left: auto; right: 0; border-right: none; border-left: 1px solid #ddd; }
    [dir="rtl"] .current-date-line { left: auto; right: auto; } /* JS handles position */
</style>

@push('scripts')
<script src="{{ asset('assets/js/gantt-chart.js') }}"></script>
<script>
    // Duration Logic
    document.addEventListener('DOMContentLoaded', function() {
        const startInput = document.getElementById('startDate');
        const endInput = document.getElementById('endDate');
        const durationDisplay = document.getElementById('durationDisplay');

        function calculateDuration() {
            if (startInput.value && endInput.value) {
                const start = new Date(startInput.value);
                const end = new Date(endInput.value);
                
                // Difference in time
                const timeDiff = end.getTime() - start.getTime();
                
                // Difference in days (inclusive)
                if (timeDiff >= 0) {
                    const daysDiff = (timeDiff / (1000 * 3600 * 24)) + 1;
                    durationDisplay.textContent = Math.round(daysDiff) + " Days";
                } else {
                    durationDisplay.textContent = "Invalid Date Range";
                }
            } else {
                durationDisplay.textContent = "-";
            }
        }

        startInput.addEventListener('change', calculateDuration);
        endInput.addEventListener('change', calculateDuration);
    });
</script>
@endpush
@endsection
